apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-api-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-api-k8s
    spec:
      containers:
        - name: spring-api-k8s-container
          image: skeres95250/spring-api:v1.0  # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8282  # The port that the container is running on in the cluster